# Generated by Django 5.1.7 on 2025-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_name_2_image_name_product_article_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark this image as the main image for the product'),
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('category', 'Category Photo'), ('product', 'Product Photo'), ('barcode', 'Barcode'), ('qrcode', 'QR Code'), ('preview', 'Preview'), ('packaging', 'Packaging'), ('logo', 'Logo')], db_index=True, default='product', help_text='Type of the image (e.g., category photo, product photo, barcode, etc.)', max_length=20),
        ),
    ]
