# Generated by Django 5.1.7 on 2025-04-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_image_is_main_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='article_number',
            field=models.CharField(blank=True, db_index=True, help_text='Category article/reference number', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['article_number'], name='store_categ_article_64b394_idx'),
        ),
    ]
