# Generated by Django 5.1.7 on 2025-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_article_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='store_categ_article_64b394_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='article_number',
        ),
        migrations.AddField(
            model_name='category',
            name='category_article',
            field=models.CharField(blank=True, db_index=True, help_text='Category article/reference code', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_article'], name='store_categ_categor_2b0902_idx'),
        ),
    ]
