# Generated by Django 5.1.7 on 2025-05-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_category_store_categ_article_64b394_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['product', '-is_active', 'price_type', 'amount']},
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='store_price_product_f6c246_idx',
        ),
        migrations.AddField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('selling', 'Selling Price'), ('purchase', 'Purchase Price'), ('regular', 'Regular Price'), ('discount', 'Discount Price'), ('wholesale', 'Wholesale Price'), ('other', 'Other Price')], db_index=True, default='regular', help_text='Type of the price (e.g., selling, purchase, discount)', max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.CharField(blank=True, help_text='Optional: further details about this price', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'price_type', 'currency')},
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'price_type', 'is_active'], name='store_price_product_2f514c_idx'),
        ),
    ]
