# Generated by Django 5.1.7 on 2025-05-30 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_price_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the warehouse', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this warehouse currently active?')),
                ('image', models.ForeignKey(blank=True, help_text='Main image for the warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='store.image')),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available quantity in stock')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Quantity reserved for orders')),
                ('minimum_stock_level', models.PositiveIntegerField(default=0, help_text='Minimum stock level for alerts')),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='store.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='store.warehouse')),
            ],
            options={
                'ordering': ['product', 'warehouse'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('counterparty_type', models.CharField(choices=[('supplier', 'Supplier'), ('buyer', 'Buyer'), ('worker', 'Worker'), ('customer', 'Customer'), ('other', 'Other')], db_index=True, help_text='Type of counterparty (e.g., supplier, buyer, worker)', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical or mailing address', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this counterparty active?')),
                ('image', models.ForeignKey(blank=True, help_text='Main image or logo for the counterparty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='store.image')),
            ],
            options={
                'ordering': ['name', 'counterparty_type'],
                'abstract': False,
                'indexes': [models.Index(fields=['slug'], name='store_count_slug_3effee_idx'), models.Index(fields=['counterparty_type', 'is_active'], name='store_count_counter_403a5b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['slug'], name='store_wareh_slug_4cb4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='store_wareh_is_acti_4db793_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='store_stock_product_2e9a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_updated'], name='store_stock_last_up_921640_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'warehouse')},
        ),
    ]
