# Generated by Django 5.1.7 on 2025-05-30 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_price_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('category', 'Category Photo'), ('product', 'Product Photo'), ('barcode', 'Barcode'), ('qrcode', 'QR Code'), ('preview', 'Preview'), ('packaging', 'Packaging'), ('logo', 'Logo'), ('audit', 'Audit Photo')], db_index=True, default='product', help_text='Type of the image (e.g., category photo, product photo, barcode, etc.)', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkerProductAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity_recorded', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_products', to=settings.AUTH_USER_MODEL)),
                ('photo_taken', models.ForeignKey(blank=True, limit_choices_to={'type': 'audit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_photos', to='store.image')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_audit_details', to='store.product')),
            ],
            options={
                'verbose_name': 'Worker Product Audit',
                'verbose_name_plural': 'Worker Product Audits',
                'ordering': ['product__name'],
                'abstract': False,
            },
        ),
    ]
